apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  destination:
    namespace: shop-microservices
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: k8s
    repoURL: https://github.com/Huzaifanasir95/Microservices-based-E-Commerce-App.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true