apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
      - name: service
        image: huzaifanasirrr/online-boutique-frontend:latest
        ports: 
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: CYMBAL_BRANDING
          value: "true"
        - name: PUBLIC_ADDR
          value: "http://a46735cf6d152472ab2a7ca6fc5f69fd-244550770.us-east-1.elb.amazonaws.com:8080"
        envFrom:
        - configMapRef:
            name: service-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080